services:
  broker:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   #Trafego TCP
      - "15672:15672" #Interface Gráfica
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data: