version: "3.9"
services:
  pg:
    image: bitnami/postgresql:latest
    ports:
      - "5483:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: invoices
    volumes:
      - ./docker:/docker-entrypoint-initdb.d

  app-invoices:
    build: .
    depends_on:
      - pg
    environment:
      DATABASE_URL: postgresql://docker:docker@pg:5432/invoices
