_format_version: "3.0"
_transform: true

services:
  - name: orders
    url: http://host.docker.internal:3333/
    routes:
      - name: api-orders
        paths:
          - /orders
        strip_path: true

  - name: invoices
    url: http://host.docker.internal:3334/
    routes:
      - name: api-invoices
        paths:
          - /invoices
        strip_path: true

plugins:
  - name: cors
    config:
      origins:
        - "*"
      methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      headers:
        - Accept
        - Content-Type
        - Authorization
