name: Pipeline CI
run-name: Pipeline CI executada por ${{ github.actor }}

on:
  workflow_dispatch:

jobs:
  Microservicos:
    name: Teste de integração dos microserviços
    runs-on: ubuntu-latest

    steps:
      # Checkout do repositório
      - name: Checagem do repositório
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      # Instalação do Docker Compose e cliente PostgreSQL
      - name: Instalação do Docker Compose e PostgreSQL Client
        run: sudo apt-get update && sudo apt-get install -y docker-compose postgresql-client

      # Inicialização do Banco de dados PostgreSQL (orders)
      - name: Build do Banco de dados orders
        working-directory: app-orders
        run: docker-compose up -d --build

      # Inicialização do Banco de dados PostgreSQL (invoices)
      - name: Build do Banco de dados invoices
        working-directory: app-invoices
        run: docker-compose up -d --build

      # Subir serviços de mensageria e observabilidade (RabbitMQ, Kong, Jaeger)
      - name: Build e Start do docker-compose de mensageria e observabilidade
        run: docker-compose -f docker-compose.yml up -d --build

      # Aguardando inicialização dos serviços
      - name: Aguardando serviços de mensageria e observabilidade
        run: |
          echo "Esperando RabbitMQ iniciar..."
          until nc -z localhost 5672; do sleep 2; done
          echo "Esperando Kong iniciar..."
          until nc -z localhost 8001; do sleep 2; done
          echo "Esperando Jaeger iniciar..."
          sleep 5

      # Executar migrations do app-orders dentro do container
      - name: Executar migrations app-orders
        working-directory: app-orders
        run: |
          docker-compose run --rm --entrypoint "" \
            -e DATABASE_URL="postgresql://docker:docker@pg:5432/orders" \
            app-orders sh -c "npm exec -- drizzle-kit generate && npm exec -- drizzle-kit migrate"

      # Executar servidor app-orders e testar endpoints
      - name: Execução do servidor app-orders
        working-directory: app-orders
        run: |
          # Iniciar o app-orders
          docker-compose run --rm -d app-orders sh -c "node --env-file=.env --experimental-strip-types --watch --no-warnings src/http/server.ts"

          # Esperar até que o serviço esteja pronto (Kong + app-orders)
          echo "Aguardando app-orders subir..."
          until curl -s -f http://localhost:8000/orders/orders > /dev/null; do
            echo "Ainda não disponível... tentando novamente em 2s"
            sleep 2
          done
          echo "app-orders pronto!"

          # Rodar os testes de requisição
          for i in {1..8}; do
            curl -s -X POST http://localhost:8000/orders/orders \
              -H "Content-Type: application/json" \
              -d '{"amount": 4}' || exit 1
          done

      # Executar servidor app-invoices
      - name: Execução do servidor app-invoices
        working-directory: app-invoices
        run: |
          docker-compose run --rm -d app-invoices sh -c "node --env-file=.env --experimental-strip-types --watch --no-warnings src/http/server.ts"
          sleep 5

      # Limpar containers
      - name: Stop do serviço docker-compose
        run: docker-compose down