
name: Pipeline CI
run-name: Pipeline CI executada por ${{ github.actor }}

on:
  workflow_dispatch:

jobs:
  Integracao:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Instalação do Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      # Subir ambiente base
      - name: Build e Start docker-compose
        run: docker-compose up -d --build

      - name: Aguardando o inicio da subida do ambiente base
        run: |
          echo "Esperando RabbitMQ iniciar..."
          until nc -z localhost 5672; do sleep 2; done
          echo "Esperando Kong iniciar..."
          until nc -z localhost 8001; do sleep 2; done
          echo "Esperando Jaeger iniciar..."
          sleep 5  # Jaeger não tem porta TCP fixa, apenas espera inicial

      # Subir app-orders e rodar migrations
      - name: Build e execução das migrations do app-orders
        working-directory: app-orders
        run: |
          docker build -t app-orders .
          docker run --rm \
            -e DATABASE_URL="postgres://review:Passw0rd2023!@host.docker.internal:5432/review" \
            app-orders sh -c "npx drizzle-kit generate && npx drizzle-kit migrate"

      # Subir app-invoices e rodar migrations
      - name: Build e execução das migrations do app-orders app-invoices
        working-directory: app-invoices
        run: |
          docker build -t app-invoices .
          docker run --rm \
            -e DATABASE_URL="postgres://review:Passw0rd2023!@host.docker.internal:5432/review" \
            app-invoices sh -c "npx drizzle-kit generate && npx drizzle-kit migrate"

      # Rodar server.ts do app-orders e testar
      - name: Execução do servidor app-orders
        working-directory: app-orders
        run: |
          npx tsc
          node ./dist/src/server.js &
          SERVER_PID=$!
          sleep 5
          for i in {1..8}; do
            curl -s -X POST http://localhost:3000 \
              -H "Content-Type: application/json" \
              -d '{"amount": 4}' || exit 1
          done
          kill $SERVER_PID

      # Limpar containers
      - name: Stop do serviço do docker-compose
        run: docker-compose down